lib/snownix_web/router.ex
defmodule SnownixWeb.Router do
  use SnownixWeb, :router

  import SnownixWeb.UserAuth
  import SnownixWeb.Project

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SnownixWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug SnownixWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :project do
    plug :browser
    plug :require_authenticated_user
    plug :fetch_current_project
    plug :required_project
  end

  ## Dashboards
  live_session :project,
    on_mount: [
      {SnownixWeb.InitAssigns, :user},
      {SnownixWeb.InitAssigns, :project}
    ] do
    scope "/", SnownixWeb do
      pipe_through [:project]

      live "/", ProjectLive.Dashboard, :index

      scope "/org", Org, as: :org do
        scope "/customers" do
          live "/", CustomerLive.Index, :index
          live "/new", CustomerLive.Index, :new
          live "/:id", CustomerLive.Index, :show
          live "/:id/edit", CustomerLive.Index, :edit
        end

        scope "/categories" do
          live "/", CategoryLive.Index, :index
          live "/new", CategoryLive.Index, :new
          live "/:id", CategoryLive.Index, :show
          live "/:id/edit", CategoryLive.Index, :edit
        end

        scope "/products" do
          live "/", ProductLive.Index, :index
          live "/new", ProductLive.Index, :new
          live "/:id", ProductLive.Index, :show
          live "/:id/edit", ProductLive.Index, :edit
        end

        scope "/invoices" do
          live "/", InvoiceLive.Index, :index
          live "/new", InvoiceLive.Index, :new
          live "/:id", InvoiceLive.Index, :show
          live "/:id/edit", InvoiceLive.Index, :edit
        end

        live "/settings", SettingsLive.Index, :settings

        live "/activities", ActivityLive.Index, :index
      end
    end
  end

  ## Liveview routes
  live_session :default,
    on_mount: [{SnownixWeb.InitAssigns, :user}, {SnownixWeb.InitAssigns, :project}] do
    scope "/", SnownixWeb do
      pipe_through [:browser]

      # Public
      live "/design", IndexLive.Design, :index

      scope "/account" do
        live "/confirm", AuthLive.Reconfirm, :reconfirm
        live "/confirm/:token", AuthLive.Confirm, :confirm
      end

      # User
      scope "/" do
        pipe_through [:require_authenticated_user]

        scope "/projects" do
          live "/", ProjectLive.Index, :index
          live "/new", ProjectLive.New, :new

          get "/open/:id", ProjectController, :open
          get "/leave", ProjectController, :leave
        end

        live "/account/settings", AccountLive.Settings, :settings
      end

      # Admin
      scope "/admin", Admin, as: :admin do
        pipe_through [:require_authenticated_user]

        # Invoice Groups
        scope "/groups" do
          live "/", GroupLive.Index, :index
          live "/new", GroupLive.Index, :new
          live "/:id/edit", GroupLive.Index, :edit

          live "/:id", GroupLive.Show, :show
          live "/:id/show/edit", GroupLive.Show, :edit
        end

        # Invoice Items
        scope "/items" do
          live "/", ItemLive.Index, :index
          live "/new", ItemLive.Index, :new
          live "/:id/edit", ItemLive.Index, :edit

          live "/:id", ItemLive.Show, :show
          live "/:id/show/edit", ItemLive.Show, :edit
        end

        # Invoices
        scope "/invoices" do
          live "/", InvoiceLive.Index, :index
          live "/new", InvoiceLive.Index, :new
          live "/:id/edit", InvoiceLive.Index, :edit

          live "/:id", InvoiceLive.Show, :show
          live "/:id/show/edit", InvoiceLive.Show, :edit
        end

        # Activities
        scope "/activities" do
          live "/", ActivityLive.Index, :index
          live "/new", ActivityLive.Index, :new
          live "/:id/edit", ActivityLive.Index, :edit

          live "/:id", ActivityLive.Show, :show
          live "/:id/show/edit", ActivityLive.Show, :edit
        end

        # Products
        scope "/products" do
          live "/", ProductLive.Index, :index
          live "/new", ProductLive.Index, :new
          live "/:id/edit", ProductLive.Index, :edit

          live "/:id", ProductLive.Show, :show
          live "/:id/show/edit", ProductLive.Show, :edit
        end

        # Units
        scope "/units" do
          live "/", UnitLive.Index, :index
          live "/new", UnitLive.Index, :new
          live "/:id/edit", UnitLive.Index, :edit

          live "/:id", UnitLive.Show, :show
          live "/:id/show/edit", UnitLive.Show, :edit
        end

        # Category
        scope "/categories" do
          live "/", CategoryLive.Index, :index
          live "/new", CategoryLive.Index, :new
          live "/:id/edit", CategoryLive.Index, :edit

          live "/:id", CategoryLive.Show, :show
          live "/:id/show/edit", CategoryLive.Show, :edit
        end

        # Projects
        scope "/projects" do
          live "/", ProjectLive.Index, :index
          live "/new", ProjectLive.Index, :new
          live "/:id/edit", ProjectLive.Index, :edit

          live "/:id", ProjectLive.Show, :show
          live "/:id/show/edit", ProjectLive.Show, :edit
        end

        # Taxs
        scope "/taxs" do
          live "/", TaxLive.Index, :index
          live "/new", TaxLive.Index, :new
          live "/:id/edit", TaxLive.Index, :edit

          live "/:id", TaxLive.Show, :show
          live "/:id/show/edit", TaxLive.Show, :edit
        end

        # Customers
        scope "/customer_users" do
          live "/", UserLive.Index, :index
          live "/new", UserLive.Index, :new
          live "/:id/edit", UserLive.Index, :edit

          live "/:id", UserLive.Show, :show
          live "/:id/show/edit", UserLive.Show, :edit
        end

        # Invoice Address
        scope "/invoice_addresses" do
          live "/", InvoiceAddressLive.Index, :index
          live "/new", InvoiceAddressLive.Index, :new
          live "/:id/edit", InvoiceAddressLive.Index, :edit

          live "/:id", InvoiceAddressLive.Show, :show
          live "/:id/show/edit", InvoiceAddressLive.Show, :edit
        end
      end

      # Auth
      scope "/auth" do
        pipe_through [:redirect_if_user_is_authenticated]

        live "/login", AuthLive.Login, :login
        live "/register", AuthLive.Register, :register
        live "/forgot-password", AuthLive.ForgotPassword, :forgot
        live "/reset-password/:token", AuthLive.ResetPassword, :reset
      end
    end
  end

  ## Controllers
  scope "/auth", SnownixWeb do
    pipe_through [:browser]

    delete "/logout", UserSessionController, :delete
  end

  scope "/auth", SnownixWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    post "/login", UserSessionController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnownixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL  which you should anyway.
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: SnownixWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

lib/snownix_web/live/org/activity_live/index.ex
defmodule SnownixWeb.Org.ActivityLive.Index do
  use SnownixWeb, :live_dashboard
  import Snownix.Helpers.TablePub

  alias Snownix.Pagination

  alias Snownix.Projects

  def mount(_params, _session, socket) do
    if connected?(socket), do: Snownix.Projects.subscribe(socket.assigns.project.id)

    {:ok,
     socket
     |> assign(:table, %{
       filters: [],
       page: 1,
       limit: 100,
       order: :desc,
       order_by: :inserted_at
     })
     |> fetch()}
  end

  def handle_params(_params, _url, socket) do
    {:noreply, socket}
  end

  def handle_info({Projects, [name, type], result}, socket) do
    case name do
      :activity ->
        handle_table_pub(
          __MODULE__,
          socket,
          :activities,
          :activity,
          {Projects, [:activity, type], result}
        )

      _ ->
        {:noreply, socket}
    end
  end

  def handle_event("order", %{"order" => order}, socket) do
    {:noreply, socket |> assign_table_order(order) |> fetch()}
  end

  def handle_event("page", %{"page" => page}, socket) do
    {:noreply, socket |> assign_table_page(page) |> fetch()}
  end

  def push_index(socket) do
    socket
  end

  defp list_activities(socket) do
    %{project: project, table: %{page: page, limit: limit, order: order, order_by: order_by}} =
      socket.assigns

    pagination =
      Projects.list_activities(project.id, order_by: order_by, order: order)
      |> Pagination.page(page, per_page: limit)

    pagination = %{
      pagination
      | items: pagination.items
    }

    socket
    |> assign(:pagination, pagination)
    |> assign(:activities, group_activities(pagination.items))
  end

  defp group_activities(items) do
    items
    |> Enum.group_by(fn e -> Timex.to_date(e.inserted_at) end, & &1)
    |> Enum.map(fn {date, items} ->
      {date,
       Enum.reduce(items, %{last: nil, values: []}, fn e, acc ->
         %{last: e, values: acc.values ++ [{acc.last && acc.last.inserted_at, e}]}
       end).values}
    end)
    |> Enum.reverse()
  end

  defp assign_table_page(socket, page) do
    page = String.to_integer(page)

    case page >= 1 and page <= socket.assigns.pagination.total do
      true ->
        socket |> assign(:table, %{socket.assigns.table | page: page})

      _ ->
        socket
    end
  end

  defp assign_table_order(socket, order) do
    order = String.to_atom(order)

    case order in Projects.Activity.__schema__(:fields) do
      true ->
        socket
        |> assign(:table, %{
          socket.assigns.table
          | order: order_by_toggle(socket),
            order_by: order
        })

      _ ->
        socket
    end
  end

  defp order_by_toggle(socket) do
    if socket.assigns.table.order == :asc do
      :desc
    else
      :asc
    end
  end

  def fetch(socket) do
    socket |> list_activities()
  end

  def render_activity(socket, assigns, row, last_inserted_at \\ nil) do
    same_prev_time = hour_format(last_inserted_at) === hour_format(row.inserted_at)

    row = Snownix.Helpers.Activity.put_links(socket, row)

    ~H"""
    <div class={"activity__block px-8 " <> (if same_prev_time, do: "", else: "pt-2")} id={"activity-#{row.id}"}>
        <div class="_meta flex items-center w-8 h-8">
          <%= if !same_prev_time do %>
            <div class="_type w-8 h-8 bg-primary text-sm rounded-full flex items-center justify-center text-white uppercase">
              <span><%= (row.action || row.type || "") |> String.slice(0,1) %></span>
            </div>
          <% end %>
        </div>
        <div class="_content flex flex-col">
          <%= if !same_prev_time do %>
            <div class="activity__time">
              <time datetime={row.inserted_at}><%= hour_format(row.inserted_at) %></time>
              <time datetime={row.inserted_at}><%= datetime_format(row.inserted_at) %></time>
            </div>
          <% end %>
          <div class={"activity__icon " <> (if same_prev_time, do: "mt-1", else: "mt-2")}>
                <a class="flex items-center space-x-2">
                  <div class={(if same_prev_time, do: "hidden md:block", else: "")}>
                    <%= render_text_avatar(assigns, row.from) %>
                  </div>
                  <span class="font-semibold"><%= row.from %></span>
                </a>
                <p>
                <span><%= get_emoji(row.action) %></span>

                  <%= for txt <- row.title |> String.split("**") do %>
                    <%= if txt == row.name do %>
                    <%= if row.link do %>
                      <%= live_patch txt, to: row.link, class: "font-bold" %>
                    <% else %>
                      <i><%= txt %></i>
                    <% end %>
                    <% else %>
                    <%= txt %>
                    <% end %>
                  <% end %>
                </p>
            </div>

            <%= if row.note do %>
                <div class="_note lg:pl-4 flex">
                    <span class="hidden lg:block text-dark text-opacity-50">
                        <svg class="w-8" viewBox="-4 10 90 100" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-width="6"
                                d="m2.69412,-2.13346c9.09909,113.20112 63.71794,96.63965 92.62963,98.87074"
                                stroke="currentColor" fill="none"></path>
                        </svg>
                    </span>
                    <p class="p-4 lg:px-6 border blrder-gray-500 rounded-lg whitespace-pre-wrap"><%= for txt <- row.note |> String.split("**") do %><%= if txt == row.name do %><strong class="font-bold"><%= txt %></strong><% else %><%= txt %><% end %><% end %></p>
                </div>
            <% end %>
        </div>
    </div>
    """
  end

  def get_emoji(action) do
    case action do
      "create" -> "➕"
      "delete" -> "🗑️"
      "update" -> "⚠️"
      _ -> ""
    end
  end
end

lib/snownix_web/live/org/category_live/form_component.ex
defmodule SnownixWeb.Org.CategoryLive.FormComponent do
  use SnownixWeb, :live_component

  alias Snownix.Products

  @impl true
  def update(%{category: category} = assigns, socket) do
    changeset = Products.change_category(category)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"category" => category_params}, socket) do
    changeset =
      socket.assigns.category
      |> Products.change_category(category_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"category" => category_params}, socket) do
    save_category(socket, socket.assigns.action, category_params)
  end

  defp save_category(socket, :edit, category_params) do
    %{project: project, current_user: user} = socket.assigns

    case Products.update_category(socket.assigns.category, category_params, project, user) do
      {:ok, _category} ->
        {:noreply,
         socket
         |> put_flash(:info, "category updated successfully")
         |> push_patch(to: socket.assigns.return_to)}

      {:error, changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_category(socket, :new, category_params) do
    %{project: project, current_user: user} = socket.assigns

    case Products.create_category(project, user, category_params) do
      {:ok, _category} ->
        {:noreply,
         socket
         |> put_flash(:info, "category created successfully")
         |> push_patch(to: socket.assigns.return_to)}

      {:error, changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/snownix_web/live/org/category_live/show_component.ex
defmodule SnownixWeb.Org.CategoryLive.ShowComponent do
  use SnownixWeb, :live_component

  def render(assigns) do
    ~H"""
    <section class="_profile space-y-2">
    <div class="py-2 px-6 rounded bg-gray-100 font-medium text-dark">
        <h3>Information</h3>
    </div>
    <div class="_category rounded-md space-y-1">
        <div>
            <label><%= gettext "Name" %></label>
            <%= @category.name %>
        </div>
        <div><label><%= gettext "Creation Date" %></label><%= @category.inserted_at %></div>
    </div>
    </section>
    """
  end
end

lib/snownix_web/live/org/invoice_live/addresses/form_component.ex
defmodule SnownixWeb.Org.InvoiceLive.Addresses.FormComponent do
  use SnownixWeb, :live_component

  @impl true
  def update(
        %{
          form: _form,
          title: _title,
          parent: _parent,
          field_name: field_name,
          selected_item: _selected_item,
          addresses: _addresses,
          added: added
        } = assigns,
        socket
      ) do
    {:ok,
     socket
     |> assign(assigns)
     |> assign(field_name_id: String.to_atom("#{field_name}_id"))}
  end

  def countries_options() do
    Snownix.Geo.countries_options()
  end
end

lib/snownix_web/live/org/category_live/form_component.html.heex
<div>
<.form
  let={f}
  for={@changeset}
  id="customer-form"
  class="space-y-2"
  phx-target={@myself}
  phx-change="validate"
  phx-submit="save">
  
    <div class="form__group">
      <%= label f, :name %>
      <%= text_input f, :name %>
      <%= error_tag f, :name %>
    </div>
  
    <div class="form__group">
      <%= label f, :contact_name %>
      <%= text_input f, :contact_name %>
      <%= error_tag f, :contact_name %>
    </div>
    <div class="form__group">
      <%= label f, :phone %>
      <%= text_input f, :phone %>
      <%= error_tag f, :phone %>
    </div>
    <div class="form__group">
      <%= label f, :email %>
      <%= text_input f, :email %>
      <%= error_tag f, :email %>
    </div>
    <div class="form__group">
      <%= label f, :website %>
      <%= text_input f, :website %>
      <%= error_tag f, :website %>
    </div>
    <div class="form__group">
      <%= label f, :currency %>
      <%= text_input f, :currency %>
      <%= error_tag f, :currency %>
    </div>
  <div>
    <%= submit "Save", phx_disable_with: "Saving...", class: "primary" %>
  </div>
</.form>

</div>

lib/snownix_web/live/org/category_live/index.html.heex
<main class="flex flex-col max-h-screen w-full">
    <section class="_header flex flex-col items-center space-y-2 md:space-y-0 md:flex-row justify-between p-8 md:pt-10">
        <div >
            <h1 class="font-semibold"><%= gettext "Categories" %></h1>
            <p class="text-gray-400">
                <%= if Enum.count(@selected_items) > 0 do %>
                    <%= Enum.count(@selected_items) %> Selected
                <% else %>
                    Manage your categories
                <% end %>
            </p>
        </div>
        <div class="flex space-x-4">
            <%= if many_selected(assigns) do %>
            <div class="flex space-x-2">
                <button class="sm" phx-click="clone-selected">
                    <%= render SnownixWeb.IconsView, "copy.svg", %{} %>
                </button>
                <button class="sm" phx-click="delete-selected" >
                    <%= render SnownixWeb.IconsView, "delete.svg", %{} %>
                </button>
            </div>
            <% end %>
            <div class="flex space-x-2">
                <button class="sm" disabled>
                    <%= render SnownixWeb.IconsView, "upload.svg", %{} %>
                    Import
                </button>
                <%= live_patch to: Routes.org_category_index_path(@socket, :new), class: "btn sm primary" do %>
                    <%= render SnownixWeb.IconsView, "plus.svg", %{} %>
                    New Category
                <% end %>
            </div>
        </div>
    </section>
 
    <div class="_table overflow-y-scroll  max-h-full h-full">
        <.live_component id="categories"  module={SnownixWeb.SharedLive.UI.TableComponent}>
            <:thead>
                <th class="w-14">
                    <div class="big__checkbox" phx-click="select" phx-value-id="all">
                        <input type="checkbox" checked={@all_selected} has-many={many_selected(assigns)}>
                        <label ></label>
                    </div>
                </th>
                <%= render_col(assigns, :contact_name, "Name") %>
                <%= render_col(assigns, :inserted_at, "Created Date") %>
                <th class="w-14"></th>
            </:thead>
            <:tbody>
                <%= for item <- @categories do %>
                    <tr 
                        id={"item-#{item.id}"} 
                        class={if (!is_nil(@category) and @category.id == item.id or item.selected), do: "active", else:  "" }
                        phx-click="select" phx-value-id={item.id}>
                        <td >
                            <%= render_checkbox(assigns, item) %>
                        </td>
                        <td><%= item.name %></td>
                        <td><%= date_format(item.inserted_at) %></td>
                        <td>
                            <div class="flex justify-end items-center space-x-2">
                                <%= live_patch to: Routes.org_category_index_path(@socket, :edit, item.id), class: "btn light  !p-1 !text-gray-500 icon" do %>
                                    <%= render SnownixWeb.IconsView, "settings.svg", %{} %>
                                <% end %>
                                <%= link to: "#", class: "btn light !p-1 !text-gray-500 icon", phx_click: "delete", phx_value_id: item.id, data: [confirm: "Are you sure?"] do %>
                                    <%= render SnownixWeb.IconsView, "delete.svg", %{} %>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </:tbody>
        </.live_component>
    </div>
    <%= form_for :table ,"#", [phx_change: "table", class: "_footer border-t px-4 py-2 justify-between flex w-full items-center"], fn f ->%>
        <div class="flex items-center space-x-2 ">
            <label>Lines </label>
            <%= select f, :limit, Enum.map(1..5, &(&1 * 5)), class: "unstyle", value: @table.limit %>
        </div>
        <div class="flex">
            <a href="#" class="btn sm light" phx-click="page" phx-value-page={@pagination.prev_page}><%= render SnownixWeb.IconsView, "arrow_prev.svg", %{} %></a>
            <div class="flex  divide-x divide-gray-300 items-center">
            <p class="px-2">Page: <span><%= @pagination.page %> / <%= @pagination.total %></span></p>
            <p class="px-2">Total: <span><%= if @pagination.has_next, do: @pagination.page * @pagination.per_page, else: @pagination.count %> / <%= @pagination.count %></span></p>
            </div>
            <a href="#" class="btn sm light" phx-click="page" phx-value-page={@pagination.next_page}><%= render SnownixWeb.IconsView, "arrow_next.svg", %{} %></a>
        </div>
        <div class="flex items-center space-x-2 ">
            <label>Page </label>
            <%= select f, :page, 1..(@pagination.total || 1), class: "unstyle", value: @table.page %>
        </div>
    <% end %>
    <div class="_view">
        <.live_component 
            id="categories" 
            open={!is_nil(@category)}
            prev={Routes.org_category_index_path(@socket,:index)}
            module={SnownixWeb.SharedLive.UI.DetailsComponent}
        >
            <:title><%= gettext "Category Details" %></:title>
            <:body>
                <%= if @live_action == :show do %>
                    <.live_component 
                        id="profile"
                        module={SnownixWeb.Org.CategoryLive.ShowComponent}
                        category={@category}
                    />
                <% end %>
                <%= if @live_action in [:new, :edit] do %>
                        <.live_component
                        module={SnownixWeb.Org.CategoryLive.FormComponent}
                        id={if is_nil(@category.id), do: "new", else: @category.id}
                        title={@page_title}
                        action={@live_action}
                        category={@category}
                        project={@project}
                        current_user={@current_user}
                        return_to={Routes.org_category_index_path(@socket, :index)}
                        />
                <% end %>
            </:body>
        </.live_component>
    </div>
</main>