lib/snownix_web/router.ex
defmodule SnownixWeb.Router do
  use SnownixWeb, :router

  import SnownixWeb.UserAuth
  import SnownixWeb.Project

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SnownixWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug SnownixWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :project do
    plug :browser
    plug :require_authenticated_user
    plug :fetch_current_project
    plug :required_project
  end

  ## Dashboards
  live_session :project,
    on_mount: [
      {SnownixWeb.InitAssigns, :user},
      {SnownixWeb.InitAssigns, :project}
    ] do
    scope "/", SnownixWeb do
      pipe_through [:project]

      live "/", ProjectLive.Dashboard, :index

      scope "/org", Org, as: :org do
        scope "/customers" do
          live "/", CustomerLive.Index, :index
          live "/new", CustomerLive.Index, :new
          live "/:id", CustomerLive.Index, :show
          live "/:id/edit", CustomerLive.Index, :edit
        end

        scope "/categories" do
          live "/", CategoryLive.Index, :index
          live "/new", CategoryLive.Index, :new
          live "/:id", CategoryLive.Index, :show
          live "/:id/edit", CategoryLive.Index, :edit
        end

        scope "/products" do
          live "/", ProductLive.Index, :index
          live "/new", ProductLive.Index, :new
          live "/:id", ProductLive.Index, :show
          live "/:id/edit", ProductLive.Index, :edit
        end

        scope "/invoices" do
          live "/", InvoiceLive.Index, :index
          live "/new", InvoiceLive.Index, :new
          live "/:id", InvoiceLive.Index, :show
          live "/:id/edit", InvoiceLive.Index, :edit
        end

        live "/settings", SettingsLive.Index, :settings

        live "/activities", ActivityLive.Index, :index
      end
    end
  end

  ## Liveview routes
  live_session :default,
    on_mount: [{SnownixWeb.InitAssigns, :user}, {SnownixWeb.InitAssigns, :project}] do
    scope "/", SnownixWeb do
      pipe_through [:browser]

      # Public
      live "/design", IndexLive.Design, :index

      scope "/account" do
        live "/confirm", AuthLive.Reconfirm, :reconfirm
        live "/confirm/:token", AuthLive.Confirm, :confirm
      end

      # User
      scope "/" do
        pipe_through [:require_authenticated_user]

        scope "/projects" do
          live "/", ProjectLive.Index, :index
          live "/new", ProjectLive.New, :new

          get "/open/:id", ProjectController, :open
          get "/leave", ProjectController, :leave
        end

        live "/account/settings", AccountLive.Settings, :settings
      end

      # Admin
      scope "/admin", Admin, as: :admin do
        pipe_through [:require_authenticated_user]

        # Invoice Groups
        scope "/groups" do
          live "/", GroupLive.Index, :index
          live "/new", GroupLive.Index, :new
          live "/:id/edit", GroupLive.Index, :edit

          live "/:id", GroupLive.Show, :show
          live "/:id/show/edit", GroupLive.Show, :edit
        end

        # Invoice Items
        scope "/items" do
          live "/", ItemLive.Index, :index
          live "/new", ItemLive.Index, :new
          live "/:id/edit", ItemLive.Index, :edit

          live "/:id", ItemLive.Show, :show
          live "/:id/show/edit", ItemLive.Show, :edit
        end

        # Invoices
        scope "/invoices" do
          live "/", InvoiceLive.Index, :index
          live "/new", InvoiceLive.Index, :new
          live "/:id/edit", InvoiceLive.Index, :edit

          live "/:id", InvoiceLive.Show, :show
          live "/:id/show/edit", InvoiceLive.Show, :edit
        end

        # Activities
        scope "/activities" do
          live "/", ActivityLive.Index, :index
          live "/new", ActivityLive.Index, :new
          live "/:id/edit", ActivityLive.Index, :edit

          live "/:id", ActivityLive.Show, :show
          live "/:id/show/edit", ActivityLive.Show, :edit
        end

        # Products
        scope "/products" do
          live "/", ProductLive.Index, :index
          live "/new", ProductLive.Index, :new
          live "/:id/edit", ProductLive.Index, :edit

          live "/:id", ProductLive.Show, :show
          live "/:id/show/edit", ProductLive.Show, :edit
        end

        # Units
        scope "/units" do
          live "/", UnitLive.Index, :index
          live "/new", UnitLive.Index, :new
          live "/:id/edit", UnitLive.Index, :edit

          live "/:id", UnitLive.Show, :show
          live "/:id/show/edit", UnitLive.Show, :edit
        end

        # Category
        scope "/categories" do
          live "/", CategoryLive.Index, :index
          live "/new", CategoryLive.Index, :new
          live "/:id/edit", CategoryLive.Index, :edit

          live "/:id", CategoryLive.Show, :show
          live "/:id/show/edit", CategoryLive.Show, :edit
        end

        # Projects
        scope "/projects" do
          live "/", ProjectLive.Index, :index
          live "/new", ProjectLive.Index, :new
          live "/:id/edit", ProjectLive.Index, :edit

          live "/:id", ProjectLive.Show, :show
          live "/:id/show/edit", ProjectLive.Show, :edit
        end

        # Taxs
        scope "/taxs" do
          live "/", TaxLive.Index, :index
          live "/new", TaxLive.Index, :new
          live "/:id/edit", TaxLive.Index, :edit

          live "/:id", TaxLive.Show, :show
          live "/:id/show/edit", TaxLive.Show, :edit
        end

        # Customers
        scope "/customer_users" do
          live "/", UserLive.Index, :index
          live "/new", UserLive.Index, :new
          live "/:id/edit", UserLive.Index, :edit

          live "/:id", UserLive.Show, :show
          live "/:id/show/edit", UserLive.Show, :edit
        end

        # Invoice Address
        scope "/invoice_addresses" do
          live "/", InvoiceAddressLive.Index, :index
          live "/new", InvoiceAddressLive.Index, :new
          live "/:id/edit", InvoiceAddressLive.Index, :edit

          live "/:id", InvoiceAddressLive.Show, :show
          live "/:id/show/edit", InvoiceAddressLive.Show, :edit
        end
      end

      # Auth
      scope "/auth" do
        pipe_through [:redirect_if_user_is_authenticated]

        live "/login", AuthLive.Login, :login
        live "/register", AuthLive.Register, :register
        live "/forgot-password", AuthLive.ForgotPassword, :forgot
        live "/reset-password/:token", AuthLive.ResetPassword, :reset
      end
    end
  end

  ## Controllers
  scope "/auth", SnownixWeb do
    pipe_through [:browser]

    delete "/logout", UserSessionController, :delete
  end

  scope "/auth", SnownixWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
    post "/login", UserSessionController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnownixWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL  which you should anyway.
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: SnownixWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

lib/snownix_web/live/user/account_live/settings.ex
defmodule SnownixWeb.AccountLive.Settings do
  use SnownixWeb, :live_dashboard

  alias Snownix.Accounts

  @tabs [
    %{
      id: "account",
      title: "Account",
      icon: "settings.svg",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis omnis similique doloribus, expedita corporis maxime harum voluptatem"
    },
    %{
      id: "security",
      title: "Security",
      icon: "security.svg",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis omnis similique doloribus, expedita corporis maxime harum voluptatem"
    },
    %{
      id: "notifications",
      title: "Notifications",
      icon: "notification.svg",
      description:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis omnis similique doloribus, expedita corporis maxime harum voluptatem"
    }
  ]
  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:tabs, @tabs)
     |> allow_upload(:avatar,
       accept: ~w(.jpg .jpeg .png .gif .txt),
       max_entries: 1,
       max_file_size: 2_000_000,
       auto_upload: true,
       progress: &handle_progress/3
     )
     |> assign(:tab, select_tab())
     |> assign(:changeset, socket.assigns.current_user |> Accounts.user_changeset(%{}))
     |> assign(
       :security_changeset,
       socket.assigns.current_user |> Accounts.user_password_changeset(%{})
     )}
  end

  def handle_event("switch-tab", %{"tab" => tab}, socket) do
    {:noreply, socket |> assign(:tab, select_tab(tab))}
  end

  def handle_event("account-validate", %{"user" => user_params}, socket) do
    {:noreply,
     socket
     |> clear_flash()
     |> assign(
       :changeset,
       socket.assigns.current_user
       |> Accounts.user_changeset(user_params)
       |> Map.put(:action, :validate)
     )}
  end

  def handle_event("account-save", %{"user" => user_params}, socket) do
    user = socket.assigns.current_user

    %{"current_password" => password} = user_params

    case Accounts.update_user(user, password, user_params) do
      {:ok, user} ->
        {:noreply,
         socket
         |> assign(:current_user, user)
         |> assign(:changeset, Accounts.user_changeset(user, user_params))
         |> put_flash(:success, gettext("Account information updated successfully."))}

      {:error, changeset} ->
        {:noreply, socket |> assign(:changeset, changeset)}
    end
  end

  def handle_event("security-validate", %{"user" => user_params}, socket) do
    {:noreply,
     socket
     |> clear_flash()
     |> assign(
       :security_changeset,
       socket.assigns.current_user
       |> Accounts.user_password_changeset(user_params)
       |> Map.put(:action, :validate)
     )}
  end

  def handle_event("security-save", %{"user" => user_params}, socket) do
    user = socket.assigns.current_user

    %{"current_password" => password} = user_params

    case Accounts.update_user_password(user, password, user_params) do
      {:ok, user} ->
        {:noreply,
         socket
         |> assign(:current_user, user)
         |> assign(:security_changeset, Accounts.user_password_changeset(user, user_params))
         |> put_flash(:success, gettext("Security information updated successfully."))}

      {:error, changeset} ->
        {:noreply, socket |> assign(:security_changeset, changeset)}
    end
  end

  # Avatar
  def handle_event("validate", _, socket), do: {:noreply, socket}

  def handle_event("delete-avatar", _, socket) do
    current_user = socket.assigns.current_user

    if !is_nil(current_user.avatar) do
      Snownix.Uploaders.AvatarUploader.delete({current_user.avatar, current_user})
    end

    case Accounts.update_user_avatar(current_user, nil) do
      {:ok, user} ->
        {:noreply, socket |> assign(:current_user, user)}

      _ ->
        {:noreply, socket}
    end
  end

  defp handle_progress(:avatar, entry, socket) do
    if entry.done? do
      current_user = socket.assigns.current_user

      consume_uploaded_entries(socket, :avatar, fn meta, entry ->
        {:ok, user} =
          Accounts.update_user_avatar(current_user, %Plug.Upload{
            content_type: entry.client_type,
            filename: entry.client_name,
            path: meta.path
          })

        {:ok, Snownix.Uploaders.AvatarUploader.url({user.avatar, user}, :original)}
      end)

      {:noreply, socket}
    else
      {:noreply, socket}
    end
  end

  # Tabs
  defp select_tab(tab \\ nil) do
    Enum.find(@tabs, List.first(@tabs), &(&1.title == tab))
  end

  def is_active_tab(current, tab) do
    current.title == tab.title
  end

  # Upload messages
  defp error_to_string(:too_large), do: gettext("File size is too large, max allowed 2MB.")
  defp error_to_string(:too_many_files), do: gettext("You have selected too many files.")

  defp error_to_string(:not_accepted),
    do: gettext("You have selected an unacceptable file type, only images are accepted.")
end

lib/snownix_web/live/user/index_live/index.ex
defmodule SnownixWeb.IndexLive.Index do
  use SnownixWeb, :live_dashboard

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(:page_title, gettext("Home"))
     |> assign_meta_tags()}
  end

  defp assign_meta_tags(socket) do
    socket
    |> put_meta_tags(%{
      page_title: gettext("Home")
    })
  end
end

lib/snownix_web/live/user/project_live/dashboard.ex
defmodule SnownixWeb.ProjectLive.Dashboard do
  use SnownixWeb, :live_dashboard
end

lib/snownix_web/live/user/project_live/index.ex
defmodule SnownixWeb.ProjectLive.Index do
  use SnownixWeb, :live_dashboard

  alias Snownix.Organizations

  def mount(_, _, socket) do
    {
      :ok,
      socket
      |> fetch()
    }
  end

  defp fetch(socket) do
    user = socket.assigns.current_user

    projects = Organizations.user_list_projects(user)
    socket |> assign(projects: projects, page_title: "My Projects")
  end
end

lib/snownix_web/live/user/project_live/new.ex
defmodule SnownixWeb.ProjectLive.New do
  use SnownixWeb, :live_dashboard

  import Snownix.Geo
  alias Snownix.Organizations
  alias Snownix.Organizations.Project

  @situtations [
    %{
      id: "freelance",
      icon: "settings",
      description: "You are a freelancer or independent contractor."
    },
    %{
      id: "company",
      icon: "settings",
      description: "You have a registred company"
    }
  ]

  @steps [
    %{
      title: "Tell us your project situation"
    },
    %{
      title: "Project information",
      prev: true
    }
  ]

  def mount(_, _, socket) do
    {:ok,
     socket
     |> assign(step: 1, situation: "company")
     |> assign_changeset()
     |> assign(situtations: @situtations, steps: @steps)}
  end

  def assign_changeset(socket) do
    socket |> assign(:changeset, Organizations.change_project(%Project{}))
  end

  def handle_event("validate", %{"project" => params}, socket) do
    changeset =
      %Project{}
      |> Organizations.change_project(params)
      |> Map.put(:action, :validate)

    {:noreply, socket |> assign(:changeset, changeset)}
  end

  def handle_event("save", %{"project" => project_params}, socket) do
    user = socket.assigns.current_user

    params = Map.merge(project_params, %{"situation" => socket.assigns.situation})

    case Organizations.create_project(user, params) do
      {:ok, project} ->
        {
          :noreply,
          socket
          |> put_flash(:success, "Project #{project.id} created successfully")
          |> redirect(to: Routes.project_index_path(socket, :index))
        }

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, socket |> put_changeset_errors(changeset) |> assign(:changeset, changeset)}
    end
  end

  def handle_event("situation", params, socket) do
    %{"situation" => situation} = params

    if @situtations |> Enum.find(&(&1.id == situation)) do
      {:noreply,
       socket
       |> assign(:step, 1)
       |> assign(:situation, situation)}
    else
      {:noreply, socket}
    end
  end

  def handle_event("next", _, socket) do
    case get_step(socket.assigns.step) do
      %{next: true} ->
        {:noreply, socket |> assign(:step, 1 + socket.assigns.step)}

      _ ->
        {:noreply, socket}
    end
  end

  def handle_event("prev", _, socket) do
    case get_step(socket.assigns.step) do
      %{prev: true} ->
        {:noreply, socket |> assign(:step, socket.assigns.step - 1)}

      _ ->
        {:noreply, socket}
    end
  end

  def get_step(index) do
    Enum.at(@steps, index)
  end

  def is_step(assigns, index), do: assigns.step == index
end

lib/snownix_web/live/user/project_live/open.ex
defmodule SnownixWeb.ProjectLive.Open do
  use SnownixWeb, :live_dashboard

  alias Snownix.Repo
  alias Snownix.Organizations

  def mount(_, _, socket) do
    {
      :ok,
      socket
    }
  end

  def handle_params(%{"id" => id}, _, socket) do
    {:noreply, socket |> fetch(id)}
  end

  defp fetch(socket, id) do
    project =
      Organizations.get_project!(id)
      |> Repo.preload(:users)

    socket
    |> assign(project: project, page_title: project.name)
  end
end

lib/snownix_web/live/user/project_live/dashboard.html.heex
Dashboard

lib/snownix_web/live/user/project_live/index.html.heex
<main class="flex flex-col p-4 md:p-10 space-y-10 w-full">
    <nav class="w-full flex justify-between">
        <div class="flex flex-col">
            <h2 class="font-semibold text-dark"><%= gettext("Projects") %></h2>
            <p><%= gettext("Here's list of your projects") %></p>
        </div>
        <div class="max-w-max">
            <%= live_redirect to: Routes.project_new_path(@socket, :new), class: "btn primary" do %>
                <%= render SnownixWeb.IconsView, "plus.svg", %{} %>
                <%= gettext("New Project") %>
            <% end %>
        </div>
    </nav>
    <%= if Enum.count(@projects) == 0 do %>
    <div class="flex flex-col items-center justify-center h-full" style="">
        <div class="flex flex-col items-center justify-center">
                <%= render SnownixWeb.IconsView, "ill-none.svg", %{} %> 
        </div>
        <div class="mt-2"><label class="font-medium">No project yet!</label></div>
        <div class="mt-2"><label class="text-gray-500">This section will contain the list of your projects.</label></div>
        <div class="mt-6">
            <%= live_redirect to: Routes.project_new_path(@socket, :new), class: "btn primary" do %>
                <%= render SnownixWeb.IconsView, "plus.svg", %{} %> 
                Get Started
            <% end %>
        </div>
    </div>
    <% else %>
    <section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 w-full">
        <%= for project <- @projects do %>
            <%= live_redirect to: Routes.project_path(@socket, :open, project.id) do %>
                <div class="space-y-2 w-full p-6 rounded-lg relative hover:bg-gray-50 cursor-pointer  bg-white border">
                    <div class="flex space-x-4">
                        <div class="relative bg-white rounded-xl bg-secondary bg-opacity-10">
                            <%= render_project_logo(assigns, project) %>
                            <img class="rounded-xl absolute object-cover w-5 h-5 -right-0.5 opacity-80 -bottom-0.5" src={"https://flagicons.lipis.dev/flags/4x3/#{String.downcase(project.country)}.svg"}>
                        </div>
                        <div class="flex items-center space-x-2">
                            <h3 class="font-medium"><%= project.name %></h3>
                        </div>
                    </div>
                    <p class="font-medium"><%= project.email %></p>
                    <p class="font-medium"><%= project.phone %></p>

                    <ul class="flex space-x-2">
                        <%= for member <- project.users do %>
                            <li>
                                <div class={"bg-white rounded-xl" <> (member.id == project.user_id && " bg-secondary bg-opacity-10" ||
                                    "")}>
                                    <%= render_user_avatar(assigns, member) %>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        <% end %>
    </section>
    <% end %>
</main>

lib/snownix_web/live/user/project_live/new.html.heex
<section class="flex flex-col items-center py-4 space-y-8 w-full flex-grow justify-center">
    <section class="space-y-5 max-w-screen-md  w-full">
        <h2 class="font-semibold">
            <%= Enum.at(@steps, @step).title %>
        </h2>

        <%# Situation %>
        <%= if is_step(assigns, 0) do %>
            <div class="space-y-2">
                <%= for item <- @situtations do %>
                    <div    
                        id={"sitatuion-#{item.id}"}
                        phx-click="situation"
                        phx-value-situation={item.id}
                        class={"flex  space-x-4 items-center 
                            p-6 rounded 
                            bg-white hover:bg-gray-50 cursor-pointer
                            border border-gray-200" <> (@situation == item.id && " bg-gray-200" ||"")}>
                        <%= render SnownixWeb.IconsView, item.icon <> ".svg", %{} %>
                        <p><%= item.description %></p>
                    </div>
                <% end %>
            </div>
        <% end %>

        <%# Project Information %>
        <%= if is_step(assigns, 1) do %>
            <.live_component module={SnownixWeb.SharedLive.AlertsComponent} flash={@flash} id="alerts" />

            <.form let={f} for={@changeset} phx-submit="save" phx-change="validate" class="space-y-4">
                <div class="form__group">
                    <%= label f, :name, gettext("Enter company name for invoice") %>
                    <%= text_input f, :name , placeholder: gettext("Name") %>
                    <%= error_tag f, :name %>
                </div>
                <div class="form__group">
                    <%= label f, :country, gettext("Country") %>
                    <%= select f, :country , countries_options(), placeholder: gettext("Country") %>
                    <%= error_tag f, :country %>
                </div>
                <div class="form__group">
                    <%= label f, :email, gettext("Email") %>
                    <%= email_input f, :email , placeholder: gettext("Email") %>
                    <%= error_tag f, :email %>
                </div>

                <div class="flex flex-col space-y-2 md:space-y-0 md:flex-row md:space-x-6">
                    <button type="button" phx-click="prev">
                        <%= render SnownixWeb.IconsView, "arrow_prev.svg", %{} %>
                        Go Back
                    </button>
                    <button class="primary" type="submit">
                        <%= render SnownixWeb.IconsView, "save.svg", %{} %>
                        Create
                    </button>
                </div>
            </.form>
        <% end %>
    </section>
</section>

lib/snownix_web/live/user/project_live/open.html.heex
<main class="flex flex-col p-4 md:p-10 space-y-10 w-full">
    <nav class="w-full flex justify-between">
        <div class="flex flex-col">
            <h2 class="font-semibold text-dark"><%= @project.name %></h2>
            <p><%= @project.email %></p>
        </div>
    </nav>
    <section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 w-full">
    </section>
</main>